# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Coupon

# Model Form Field configuration
form: $/bookrr/product/models/coupons/fields.yaml

# Model Class name
modelClass: Bookrr\Product\Models\Coupons

# Default redirect location
defaultRedirect: bookrr/product/coupons

# Create page
create:
    title: Create Coupon
    redirect: bookrr/product/coupons/update/:id
    redirectClose: bookrr/product/coupons

# Update page
update:
    title: Edit Coupon
    redirect: bookrr/product/coupons
    redirectClose: bookrr/product/coupons

# Preview page
preview:
    title: Preview Coupon
